typography_spectrum: 0.7864120993763208
color:
  brandStrength: 0.02174186846241355
  lightness: 0.9814976612105966
  saturation: 0.2903132594656199
  rhythmicContrast: 0.35129938600584865
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
layout_spectrum: 0.345473155612126
name: caminhos de sangue
navigation:
  - name: primeira parte da trilogia
    url: 'http://thegrid.ai/adormecida/'
    type: external
title: Caminhos de Sangue
description: terceira parte da trilogia das assassinas
